from abc import ABC, abstractmethod
from typing import List, Dict, Any

class BaseTeacherExtractor(ABC):
    """
    Abstract Base Class for Teacher Knowledge Extractors.
    Supports both local inference engines (vLLM / Transformers) and Cloud APIs (Gemini / OpenAI).
    """

    @abstractmethod
    def generate_batch(self, prompts: List[str]) -> List[str]:
        """
        Receives a list of formatted prompts and returns raw text outputs generated by the Teacher.
        """
        pass
